### ISSUE TITLE
Current status of project

### ISSUE THREAD

**Issue by davydovanton** [sebastjan-hribar/tachiban#5]
Hey, thanks for this prototype.

Could you say what the status of this project? You want to continue work on it, or you need some help?

**Comment by sebastjan-hribar** [comment]
Hi,
thank you for asking.

I was about to release it as 0.5 and to be compatible with Hanami 1.0.

I've bumped the dependencies for controller and model from 0.6 to 1.0 and now some tests broke. @vasspilka helped me debug it and it seems that it's connected to how params stores entities.

Before in the action call (for testing only) I could do `@user = params[:user]` and then `@user.some_method`

Now, with 1.0 `some_method` call returns `NoMethodError: undefined method 'name' for #<Hash:0x000000024a9938>` so basically I should probably just refactor specs to provide the user object from `params.env[:user]` instead of `params[:user]`.

Other than that, I'd appreciate a sanity check prior to release, since I have very little experience with releasing gems.

Tachiban 0.5 would support authentication, while my goal for 1.0 is to add support for role based authorization as well.

**Comment by sebastjan-hribar** [comment]
Tachiban was released under 0.3 as I've decided to postpone the password reset support.
